- hosts: default
  gather_facts: true
  become: true

  tasks:

  - name: Get host variables
    include_vars:
      file: ../host_vars/vars.yml

  - name: Install software packages
    apt:
      name:
        - nginx

  - name: Create javascript directory
    file:
      path: /var/www/html/js/
      state: directory

  - name: Copy js files into place
    copy:
      src: "{{ item }}"
      dest: /var/www/html/js
    with_fileglob: ../files/js/*

  - name: Create css directory
    file:
      path: /var/www/html/css/
      state: directory

  - name: Copy css files into place
    copy:
      src: "{{ item }}"
      dest: /var/www/html/css/
    with_fileglob: ../files/css/*

  - name: Copy HTML files into place
    copy:
      src: "{{ item }}"
      dest: /var/www/html/
    with_fileglob: ../files/*
